"""init

Revision ID: 3f81b707dbe4
Revises:
Create Date: 2021-10-06 12:33:17.827125

"""
from pathlib import Path

from alembic import op
# revision identifiers, used by Alembic.
from sqlalchemy import text

revision = 'e667733376be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
   dump_path = Path(__file__).parent.parent.absolute() / 'schema.dump'

   with open(dump_path, 'r') as sql_reader:
       op.execute(text(sql_reader.read()))

   op.execute(text('SET search_path = public'))


def downgrade():
   # ### commands auto generated by Alembic - please adjust! ###
   pass
   # ### end Alembic commands ###
